language: node_js
sudo: required
node_js:
- '4.2'
before_install:

  # Global install some npm
  - npm install -g grunt-cli

  # Install kalabox
  - sudo apt-get -y update
  - sudo apt-get -y install iptables cgroup-bin bridge-utils curl
  - curl -fsSL -o /tmp/kalabox.deb "http://installer.kalabox.io/kalabox-latest-dev.deb"
  - sudo dpkg -i /tmp/kalabox.deb

before_script:

  # Nice dev helpers to verify our env
  - ./scripts/travis-env.sh

  # Sanity checks
  - node --version
  - npm --version
  - grunt --version
  - kbox version
  - kbox create || true

script:

  # Run code tests
  - grunt test:code

cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalabox.io
    - alec@kalabox.io
    on_success: always
env:
  global:
  - DOCKER_HOST: tcp://10.13.37.100:2375
