#
# Wraith tooling.
#
wraith:
  image: bbcnews/wraith:latest
  command: 'true'
  volumes:
    - $KALABOX_APP_ROOT:/src
    - $KALABOX_APP_ROOT/config/wraith:/root
  working_dir: /root
  stdin_open: true
  tty: true
