#
# Wraith tooling.
#
wraith:
  image: bbcnews/wraith:latest
  command: 'true'
  volumes:
    - $KALABOX_APP_ROOT:/src
  volumes_from:
    - data
  working_dir: $KALABOX_CLI_WORKING_DIR
  stdin_open: true
  tty: true
